#InfluxDB Configurations
influxDBUrl: http://localhost:8086
influxDBUserName: admin
influxDBUserPassword: admin
influxDB_Name: Demo
influxDB_TableName: Alerts_29_1

#AWS S3 
awsS3Enable: false
awsAccessKeyId: test 
awsSecretAccessKey: 123 

#RabbitMQ Connection Configurations
rabbitMQHost: localhost
rabbitMQport: 5672
rabbitMQuser: guest
rabbitMQpass: guest
rabbitMQName: emailAlerts

#KairosDB
kairosDBRestUrl: http://localhost:8080
kairosDBMetricName: Alerts


