#InfluxDB Configurations
influxDBUrl: http://localhost:8086
influxDBUserName: admin
influxDBUserPassword: admin
influxDB_Name: Demo
influxDB_TableName: Alerts_29_1

#AWS S3 
awsS3Enable: false
awsAccessKeyId: 
awsSecretAccessKey: 

#RabbitMQ Connection Configurations
rabbitMQHost: localhost
rabbitMQport: 5672
rabbitMQuser: guest
rabbitMQpass: guest
rabbitMQName: emailAlerts
rabbitMQName_worker: task_queue_29_1 

#KairosDB
kairosDBRestUrl: http://localhost:8080
kairosDBMetricName: Alerts01


