#InfluxDB Configurations
influxDBUrl: http://localhost:8086
influxDBUserName: admin
influxDBUserPassword: admin
influxDB_Name: Demo
influxDB_TableName: Alerts77

#AWS S3 
awsAccessKeyId: AKIAIHMHKLL6ZIKUDFPA
awsSecretAccessKey: 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

#RabbitMQ Connection Configurations
rabbitMQHost: localhost
rabbitMQport: 5672
rabbitMQuser: guest
rabbitMQpass: guest
rabbitMQName: hello1
rabbitMQName_worker: task_queue1 

